import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-[100vh]">
        <div className="flex flex-row flex-nowrap  ">
          <div>
            <h1 className="font-bold text-5xl text-white relative mt-[20vh]">
              Kelvin Ng'eno
            </h1>

            <div className={[`text-white`, " mt-10"].join(" ")}>
              <ul>
                <li>
                  <a
                    href="about"
                    className={[`text-white`, styles.work_link].join(" ")}
                  >
                    App developer
                  </a>
                </li>
                <li>
                  <a
                    href=""
                    className={[`text-white`, styles.work_link].join(" ")}
                  >
                    Web developer
                  </a>
                </li>
                <li>
                  <a
                    href=""
                    className={[`text-white`, styles.work_link].join(" ")}
                  >
                    Designer
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div className="ml-20">
            <img
              src="/circlebg.png"
              className=" h-[600px] w-[600px] object-contain"
            />
          </div>
        </div>
      </div>
    </div>
  );
}
